spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token:
      secret: ${JWT_SECRET:90472d6ad2bf1209a3b2d9491fe8bb683e390efa5c5cd636e3c42520e6575c52}